### ISSUE TITLE
안녕하세요. 반갑습니다. 작성하느라 고생 많으셨습니다.

### ISSUE THREAD

**Issue by corazzon** [fingersdanny/CovidCrawler#1]
문서화를 너무 잘 작성해 주셨습니다. 실행영상까지 작성한 부분이 인상적입니다. kosis 페이지를 따로 찾아 수집한 점도 인상적이에요. 셀레니움의 크롬드라이버는 따로 커밋하지 않고 문서에 관련 링크를 추가해도 괜찮겠습니다. 셀레니움을 통해 수집해 주셨는데 관련 Oepn API를 찾아서 수집하는 방법도 있으니 찾아보세요. 셀레니움은 수집과정을 눈으로 볼 수 있는 점이 좋지만 리소스를 많이 사용하는 편입니다.

**Comment by hodadako** [comment]
리뷰 감사합니다. Selenium이 리소스를 많이 사용하는지 실행하여 직접 확인해보고 어떤식으로 바꾸면 좋을지 한번 생각해보겠습니다.
