### ISSUE TITLE
패키지명을 쓰는 습관을 들이시길 바랍니다

### ISSUE THREAD

**Issue by easyspubjava** [fingersdanny/CovidCrawler#2]
자바의 모든 클래스는 패키지 하위에 놓여야하고 패키지 명은 클래스의 모음입니다. 클래스가 하나더라도 패키지로 구분하는 습관을 들여주세요

**Comment by hodadako** [comment]
리뷰 감사합니다. ~~6개월 뒤에 한번 다시 확인하고 왜 이렇게 했는지 반성해보겠습니다~~  😳

**Comment by easyspubjava** [comment]
화이팅!!!
